#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'
cookbook 'apache2', '>= 1.0.0'
cookbook 'postgresql', '>= 1.0.0'
cookbook 'database', '>= 1.0.0'
cookbook 'apt', '>= 1.0.0'
